// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBer4yRl-iMy6rBNqxdU4PPkvnSXf6OTrA',
    appId: '1:607440639793:web:2f0d470bd5eab22f884210',
    messagingSenderId: '607440639793',
    projectId: 'chatappproject-f51f9',
    authDomain: 'chatappproject-f51f9.firebaseapp.com',
    storageBucket: 'chatappproject-f51f9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmXTOFQl3Zx7Y64O_xl4aA7vSkjMz652s',
    appId: '1:607440639793:android:bcdd8c7ffcfa26fb884210',
    messagingSenderId: '607440639793',
    projectId: 'chatappproject-f51f9',
    storageBucket: 'chatappproject-f51f9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdR9QdXM5pK-o25eBSzGoON0KY3SyECgw',
    appId: '1:607440639793:ios:72e6c93cecc048e6884210',
    messagingSenderId: '607440639793',
    projectId: 'chatappproject-f51f9',
    storageBucket: 'chatappproject-f51f9.firebasestorage.app',
    androidClientId: '607440639793-afgfm476384uhdapn5grboltso97gkah.apps.googleusercontent.com',
    iosBundleId: 'com.asg.school',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdR9QdXM5pK-o25eBSzGoON0KY3SyECgw',
    appId: '1:607440639793:ios:6d551907a6648b93884210',
    messagingSenderId: '607440639793',
    projectId: 'chatappproject-f51f9',
    storageBucket: 'chatappproject-f51f9.firebasestorage.app',
    androidClientId: '607440639793-afgfm476384uhdapn5grboltso97gkah.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs8Lhljb_LwmfwY5Xy6hOl-SpcLSSKd8o',
    appId: '1:607440639793:web:2034e89500c5b616884210',
    messagingSenderId: '607440639793',
    projectId: 'chatappproject-f51f9',
    authDomain: 'chatappproject-f51f9.firebaseapp.com',
    storageBucket: 'chatappproject-f51f9.firebasestorage.app',
  );
}
